### ISSUE TITLE
fix effect 

### ISSUE THREAD

**Issue by scamnegra** [Sha3de/PotionOverlay#2]
[To make the new effects appear not from above but from below, it will be much more convenient and add a size adjustment that is inconvenient now

**Comment by Heisenkebab** [comment]
I do not understand what you mean. Please provide more information and if possible a screenshot of the problem.

**Comment by scamnegra** [comment]
and the right shift menu, you can shuffle the effects panel from the shuffled panel, new effects go up, this is inconvenient, it would be better if they went down, and it would also be nice if you could adjust the size of the hud

**Comment by Heisenkebab** [comment]
Ok thank you for your more detailed explanation, i unterstand the problem now.
It will be fixed soon.

**Comment by scamnegra** [comment]
thanks
